const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
async function load(){const r=await Promise.all(['programas','episodios','programacion'].map(x=>fetch('data/'+x+'.json').then(r=>r.json())));return{programas:r[0],episodios:r[1],programacion:r[2]}}
function header(){return '<header><div class="nav"><a class="brand" href="index.html">OCARINA <span>TV</span></a><nav><a href="index.html">Señal</a><a href="episodio.html">Episodios</a><a href="programacion.html">Programación</a><a href="programas.html">Programas</a><a href="archivo.html">Archivo</a></nav></div></header>'}
function foot(){return '<footer>OCARINA TV · San Patricio del Chañar · Una producción de Ocarina Producciones</footer>'}
function shell(t,b){document.title=t+' · OCARINA TV';document.body.innerHTML=header()+b+foot();if('serviceWorker' in navigator)navigator.serviceWorker.register('sw.js').catch(()=>{})}
function card(e){return '<article class="card"><img class="thumb" src="'+esc(e.thumbnail)+'" alt="" loading="lazy"><div class="cardbody"><span class="tag">'+esc(e.categoria)+'</span><h3>'+esc(e.titulo)+'</h3><p>'+esc(e.descripcion)+'</p><div class="chips">'+(e.tags||[]).map(t=>'<span>'+esc(t)+'</span>').join('')+'</div><a class="play" href="episodio.html?id='+encodeURIComponent(e.id)+'">▶ VER EPISODIO</a></div></article>'}
async function renderPrograms(){const d=await load(),q=new URLSearchParams(location.search),id=q.get('id');if(id){const p=d.programas.find(x=>x.id===id);const eps=d.episodios.filter(x=>x.programaId===id);shell(p?.nombre||'Programa','<main><div class="kicker">PROGRAMA</div><h1>'+esc(p?.nombre||'No encontrado')+'</h1><p class="muted">'+esc(p?.descripcion||'')+'</p><div class="grid">'+eps.map(card).join('')+'</div><p class="muted">'+eps.length+' episodios publicados.</p></main>');return}shell('Programas','<main><div class="kicker">OCARINA TV</div><h1>Programas</h1><p class="muted">Cada programa es una colección editorial independiente.</p><div class="programs">'+d.programas.map(p=>'<a class="program" href="programas.html?id='+encodeURIComponent(p.id)+'"><b>'+esc(p.nombre)+'</b><span>'+esc(p.descripcion)+' · '+esc(p.categoria)+'</span></a>').join('')+'</div></main>')}
async function renderSchedule(){const d=await load();shell('Programación','<main><div class="kicker">GRILLA EDITORIAL</div><h1>Programación</h1><p class="muted">Programación editorial. No representa transmisión lineal 24/7.</p><div class="timeline">'+d.programacion.map(s=>'<div class="slot '+(s.orden===1?'live':'')+'"><b>'+esc(s.etiqueta)+' · '+esc(s.titulo)+'</b><small>'+esc(s.descripcion)+'</small></div>').join('')+'</div></main>')}
async function renderArchive(){const d=await load(),q=new URLSearchParams(location.search),pid=q.get('programa');let list=pid?d.episodios.filter(e=>e.programaId===pid):d.episodios;shell('Archivo','<main><div class="kicker">ARCHIVO TERRITORIAL</div><h1>Archivo Ocarina</h1><input class="search" id="search" placeholder="Buscar episodio, tema, territorio o etiqueta…" autofocus><p class="muted" id="count"></p><div class="grid" id="list"></div></main>');const draw=()=>{const term=document.getElementById('search').value.toLowerCase().trim();const out=list.filter(e=>([e.titulo,e.descripcion,e.categoria,e.territorio,e.paraje,...(e.tags||[]),...(e.protagonistas||[])].filter(Boolean).join(' ')).toLowerCase().includes(term));document.getElementById('list').innerHTML=out.map(card).join('');document.getElementById('count').textContent=out.length+' episodios encontrados'};document.getElementById('search').oninput=draw;draw()}
async function renderEpisode(){const d=await load(),id=new URLSearchParams(location.search).get('id'),e=d.episodios.find(x=>x.id===id);if(!e){shell('Episodio no encontrado','<main><h1>Episodio no encontrado</h1><p class="muted">La pieza solicitada no existe en el catálogo.</p><a class="btn" href="archivo.html">Volver al archivo</a></main>');return}const p=d.programas.find(x=>x.id===e.programaId),related=d.episodios.filter(x=>x.id!==e.id&&((x.tags||[]).some(t=>(e.tags||[]).includes(t))||x.programaId===e.programaId)).slice(0,4);document.title=e.titulo+' · OCARINA TV';document.head.querySelector('meta[name="description"]')?.setAttribute('content',e.descripcion+' · OCARINA TV');shell(e.titulo,'<main class="detail"><div class="kicker">'+esc(p?.nombre||'OCARINA TV')+' · '+esc(e.categoria)+'</div><h1>'+esc(e.titulo)+'</h1><div class="video"><iframe src="https://www.youtube.com/embed/'+encodeURIComponent(e.videoId)+'?rel=0" title="'+esc(e.titulo)+'" allowfullscreen></iframe></div><p>'+esc(e.descripcion)+'</p><div class="meta"><span>Territorio: '+esc(e.territorio||'No especificado')+'</span><span>Fecha: '+esc(e.fecha||'No cargada')+'</span><span>Duración: '+esc(e.duracion||'No cargada')+'</span></div><div class="chips">'+(e.tags||[]).map(t=>'<span>'+esc(t)+'</span>').join('')+'</div><p class="muted">Programa: <a href="programas.html?id='+encodeURIComponent(e.programaId)+'">'+esc(p?.nombre||'Archivo Ocarina')+'</a> · Estado: '+esc(e.estado)+'</p><a class="btn" href="archivo.html">← Volver al archivo</a><section class="section"><div class="kicker">CONTENIDO RELACIONADO</div><h2>También puede interesarte</h2><div class="grid">'+related.map(card).join('')+'</div></section></main>')}
window.OTV={load,renderPrograms,renderSchedule,renderArchive,renderEpisode};