const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
async function load(){const r=await Promise.all(['programas','episodios','programacion'].map(x=>fetch('data/'+x+'.json').then(r=>r.json())));return{programas:r[0],episodios:r[1],programacion:r[2]}}
function header(){return '<header><div class="nav"><a class="brand" href="index.html">OCARINA <span>TV</span></a><nav><a href="index.html">Señal</a><a href="episodio.html">Episodios</a><a href="programacion.html">Programación</a><a href="programas.html">Programas</a><a href="archivo.html">Archivo</a></nav></div></header>'}
function foot(){return '<footer>OCARINA TV · San Patricio del Chañar · Una producción de Ocarina Producciones</footer>'}
function shell(t,b){document.title=t+' · OCARINA TV';document.body.innerHTML=header()+b+foot()}
async function renderPrograms(){const d=await load();shell('Programas','<main><div class="kicker">OCARINA TV</div><h1>Programas</h1><p class="muted">Estructura editorial del canal.</p><div class="programs">'+d.programas.map(p=>'<a class="program" href="archivo.html?programa='+encodeURIComponent(p.id)+'"><b>'+esc(p.nombre)+'</b><span>'+esc(p.descripcion)+' · '+esc(p.categoria)+'</span></a>').join('')+'</div></main>')}
async function renderSchedule(){const d=await load();shell('Programación','<main><div class="kicker">GRILLA EDITORIAL</div><h1>Programación</h1><p class="muted">Programación editorial. No representa transmisión lineal 24/7.</p><div class="timeline">'+d.programacion.map(s=>'<div class="slot '+(s.orden===1?'live':'')+'"><b>'+esc(s.etiqueta)+' · '+esc(s.titulo)+'</b><small>'+esc(s.descripcion)+'</small></div>').join('')+'</div></main>')}
async function renderArchive(){const d=await load(),q=new URLSearchParams(location.search),pid=q.get('programa');let list=pid?d.episodios.filter(e=>e.programaId===pid):d.episodios;shell('Archivo','<main><div class="kicker">ARCHIVO TERRITORIAL</div><h1>Archivo Ocarina</h1><input class="search" id="search" placeholder="Buscar episodio, tema o palabra clave…"><p class="muted" id="count"></p><div class="list" id="list"></div></main>');const draw=()=>{const term=document.getElementById('search').value.toLowerCase();const out=list.filter(e=>(e.titulo+' '+e.descripcion+' '+e.categoria).toLowerCase().includes(term));document.getElementById('list').innerHTML=out.map(e=>'<a href="episodio.html?id='+encodeURIComponent(e.id)+'"><span class="tag">'+esc(e.categoria)+'</span><h3>'+esc(e.titulo)+'</h3><span class="muted">'+esc(e.descripcion)+'</span></a>').join('');document.getElementById('count').textContent=out.length+' episodios encontrados'};document.getElementById('search').oninput=draw;draw()}
async function renderEpisode(){const d=await load(),id=new URLSearchParams(location.search).get('id'),e=d.episodios.find(x=>x.id===id);if(!e){shell('Episodio no encontrado','<main><h1>Episodio no encontrado</h1><a class="btn" href="archivo.html">Volver al archivo</a></main>');return}const p=d.programas.find(x=>x.id===e.programaId);shell(e.titulo,'<main class="detail"><div class="kicker">'+esc(p?.nombre||'OCARINA TV')+' · '+esc(e.categoria)+'</div><h1>'+esc(e.titulo)+'</h1><div class="video"><iframe src="https://www.youtube.com/embed/'+encodeURIComponent(e.videoId)+'?rel=0" title="'+esc(e.titulo)+'" allowfullscreen></iframe></div><p>'+esc(e.descripcion)+'</p><p class="muted">Programa: '+esc(p?.nombre||'Archivo Ocarina')+' · Estado: '+esc(e.estado)+'</p><a class="btn" href="archivo.html">← Volver al archivo</a></main>')}
window.OTV={load,renderPrograms,renderSchedule,renderArchive,renderEpisode};